### ISSUE TITLE
Jellyfish binary availability?

### ISSUE THREAD

**Issue by fplazaonate** [iric-soft/pyJellyfish#5]
Hi,

I have successfully installed pyJellyfish and I can import the package.
I was wondering if the jellfyish binary is also installed?

**Comment by feghalya** [comment]
Hi,

I have added a commit to master that installs the jellyfish binary in addition to the python bindings. You can install using `pip install git+https://github.com/iric-soft/pyJellyfish.git`.

Albert

**Comment by fplazaonate** [comment]
Thanks Albert for this quick fix.
Could you release these changes on PyPi?

**Comment by feghalya** [comment]
pyJellyfish v1.3.1 will include the jellyfish binary in the installation and is now available on PyPI. I will closing this issue, but feel free to open a new one if any other issues arise.
